# Generated by Django 5.2.14 on 2026-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
